'use client';

import React, { useState } from 'react';
import { ProjectAnalysisResult } from '../../types/project';
import {
  X,
  FileDown,
  Printer,
  FileText,
  Code,
  Check,
  Copy,
  Table,
  CheckCircle2,
} from 'lucide-react';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  result: ProjectAnalysisResult;
}

export const ExportModal: React.FC<ExportModalProps> = ({ isOpen, onClose, result }) => {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const projectName = result.project?.name || 'Project_Scope';
  const cleanName = projectName.toLowerCase().replace(/[^a-z0-9]+/g, '_');

  // 1. Download Markdown PRD
  const handleDownloadMarkdown = () => {
    const md = `# Project Scope Dossier: ${result.project?.name}
*Generated by ProjectScope AI Engine*

## 1. Executive Summary
${result.explanation?.summary || 'Comprehensive AI-driven requirement analysis and architecture breakdown.'}

- **Total Estimated Effort:** ${result.total_estimated_hours?.toFixed(1)} Hours
- **Expected Cost:** $${result.cost?.total?.expected?.toLocaleString() || 'N/A'}
- **Target Timeline:** ${result.timeline?.total_working_days || 20} Working Days
- **Calculated Risk Level:** ${result.risk_level || 'HIGH'}

---

## 2. Extracted Features (${result.features.length})
${result.features
  .map(
    (f) =>
      `### ${f.canonical_name}\n- **Priority:** ${f.priority}\n- **Complexity:** ${f.complexity}/5\n- **Description:** ${f.description}\n`
  )
  .join('\n')}

---

## 3. Engineering Tasks Breakdown (${result.tasks.length})
| ID | Discipline | Title | Estimated Hours |
|---|---|---|---|
${result.tasks
  .map((t) => `| ${t.id} | ${t.category || 'General'} | ${t.title} | ${t.estimated_hours}h |`)
  .join('\n')}

---

## 4. Financial & Role Allocations
| Role | Hours | Est. Cost |
|---|---|---|
${Object.entries(result.summary || {})
  .map(([role, data]) => `| ${role} | ${data.total_hours}h | $${data.estimated_cost?.toLocaleString()} |`)
  .join('\n')}

---

## 5. Risk Assessment & Mitigations
${(result.risks?.top_risks || [])
  .map(
    (r) =>
      `- **${r.name}** (${r.risk_level} Risk)\n  - *Mitigation:* ${r.mitigation}\n  - *Owner:* ${r.owner}`
  )
  .join('\n')}
`;

    const blob = new Blob([md], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${cleanName}_prd_dossier.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  // 2. Download JSON Raw Telemetry
  const handleDownloadJson = () => {
    const blob = new Blob([JSON.stringify(result, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${cleanName}_telemetry.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  // 3. Download Jira / CSV Tasks
  const handleDownloadCsv = () => {
    const headers = ['Issue ID', 'Summary', 'Description', 'Discipline', 'Estimated Hours', 'Priority'];
    const rows = result.tasks.map((t) => [
      t.id,
      `"${t.title.replace(/"/g, '""')}"`,
      `"${t.description.replace(/"/g, '""')}"`,
      t.category || 'Engineering',
      t.estimated_hours,
      t.priority || 'HIGH',
    ]);

    const csvContent = [headers.join(','), ...rows.map((r) => r.join(','))].join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${cleanName}_jira_tasks.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  // 4. Print Executive Dossier
  const handlePrint = () => {
    window.print();
  };

  // 5. Copy Executive Summary
  const handleCopySummary = () => {
    const summaryText = `Project: ${result.project?.name}\nTotal Effort: ${result.total_estimated_hours?.toFixed(0)}h\nExpected Budget: $${result.cost?.total?.expected?.toLocaleString() || 'N/A'}\nTimeline: ${result.timeline?.total_working_days || 20} working days\nRisk Profile: ${result.risk_level}\n\nFeatures:\n${result.features.map((f) => `- ${f.canonical_name}: ${f.description}`).join('\n')}`;
    navigator.clipboard.writeText(summaryText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-sm animate-in fade-in duration-200">
      <div className="relative w-full max-w-lg bg-white rounded-2xl shadow-2xl border border-slate-200 overflow-hidden">
        {/* Header */}
        <div className="bg-gradient-to-r from-sky-600 to-indigo-700 p-6 text-white flex items-center justify-between">
          <div className="flex items-center space-x-3">
            <div className="p-2 rounded-xl bg-white/10 backdrop-blur-sm">
              <FileDown className="w-5 h-5 text-sky-200" />
            </div>
            <div>
              <h3 className="text-lg font-bold">Export Project Scope</h3>
              <p className="text-xs text-sky-100">
                Multi-format engineering reports and issue tracking exports
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-white/80 hover:text-white hover:bg-white/10 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Options */}
        <div className="p-6 space-y-3">
          {/* Printable Dossier */}
          <button
            onClick={handlePrint}
            className="w-full p-4 rounded-xl border border-slate-200 hover:border-sky-500 hover:bg-sky-50/50 text-left transition-all flex items-center justify-between group"
          >
            <div className="flex items-center space-x-3">
              <div className="p-2.5 rounded-xl bg-sky-50 group-hover:bg-sky-100 text-sky-700">
                <Printer className="w-5 h-5" />
              </div>
              <div>
                <div className="font-bold text-sm text-slate-900 group-hover:text-sky-700">
                  Print-Ready Executive Dossier (PDF)
                </div>
                <p className="text-xs text-slate-500">
                  Formatted summary for client presentations, stakeholders & board reviews.
                </p>
              </div>
            </div>
          </button>

          {/* Markdown PRD */}
          <button
            onClick={handleDownloadMarkdown}
            className="w-full p-4 rounded-xl border border-slate-200 hover:border-indigo-500 hover:bg-indigo-50/50 text-left transition-all flex items-center justify-between group"
          >
            <div className="flex items-center space-x-3">
              <div className="p-2.5 rounded-xl bg-indigo-50 group-hover:bg-indigo-100 text-indigo-700">
                <FileText className="w-5 h-5" />
              </div>
              <div>
                <div className="font-bold text-sm text-slate-900 group-hover:text-indigo-700">
                  Markdown PRD Specification (.md)
                </div>
                <p className="text-xs text-slate-500">
                  Structured document ready for GitHub README, Notion, or internal wikis.
                </p>
              </div>
            </div>
          </button>

          {/* Jira / CSV Tasks */}
          <button
            onClick={handleDownloadCsv}
            className="w-full p-4 rounded-xl border border-slate-200 hover:border-emerald-500 hover:bg-emerald-50/50 text-left transition-all flex items-center justify-between group"
          >
            <div className="flex items-center space-x-3">
              <div className="p-2.5 rounded-xl bg-emerald-50 group-hover:bg-emerald-100 text-emerald-700">
                <Table className="w-5 h-5" />
              </div>
              <div>
                <div className="font-bold text-sm text-slate-900 group-hover:text-emerald-700">
                  Jira / Linear Issue Import (.csv)
                </div>
                <p className="text-xs text-slate-500">
                  Includes {result.tasks.length} tasks formatted for bulk import into issue trackers.
                </p>
              </div>
            </div>
          </button>

          {/* Raw JSON Telemetry */}
          <button
            onClick={handleDownloadJson}
            className="w-full p-4 rounded-xl border border-slate-200 hover:border-purple-500 hover:bg-purple-50/50 text-left transition-all flex items-center justify-between group"
          >
            <div className="flex items-center space-x-3">
              <div className="p-2.5 rounded-xl bg-purple-50 group-hover:bg-purple-100 text-purple-700">
                <Code className="w-5 h-5" />
              </div>
              <div>
                <div className="font-bold text-sm text-slate-900 group-hover:text-purple-700">
                  Raw Analysis Telemetry (.json)
                </div>
                <p className="text-xs text-slate-500">
                  Complete machine-readable payload with hybrid estimates and risk graphs.
                </p>
              </div>
            </div>
          </button>
        </div>

        {/* Footer with Quick Copy */}
        <div className="p-4 bg-slate-50 border-t border-slate-100 flex items-center justify-between">
          <button
            onClick={handleCopySummary}
            className="inline-flex items-center space-x-1.5 text-xs font-semibold text-slate-700 hover:text-sky-600 transition-colors"
          >
            {copied ? <Check className="w-4 h-4 text-emerald-600" /> : <Copy className="w-4 h-4" />}
            <span>{copied ? 'Summary Copied to Clipboard!' : 'Copy Executive Brief'}</span>
          </button>

          <button
            onClick={onClose}
            className="px-4 py-1.5 rounded-xl text-xs font-semibold text-slate-500 hover:bg-slate-200/60"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
