"""
Phase 26: Prometheus Metrics
Application metrics for monitoring and alerting.
"""

import platform

from prometheus_client import Counter, Gauge, Histogram, Info

# ============================================
# APPLICATION INFO
# ============================================

APP_INFO = Info("projectscope_app", "Application information")
APP_INFO.info({
    "version": "0.3.0",
    "python": platform.python_version(),
})


# ============================================
# HTTP METRICS
# ============================================

REQUEST_COUNT = Counter(
    "projectscope_http_requests_total",
    "Total HTTP requests",
    ["method", "endpoint", "status"],
)

REQUEST_DURATION = Histogram(
    "projectscope_http_request_duration_seconds",
    "HTTP request duration",
    ["method", "endpoint"],
    buckets=[0.01, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0],
)

REQUEST_IN_PROGRESS = Gauge(
    "projectscope_http_requests_in_progress",
    "HTTP requests currently in progress",
)

REQUEST_ERRORS = Counter(
    "projectscope_http_errors_total",
    "HTTP errors by type",
    ["method", "endpoint", "error_type"],
)


# ============================================
# AI / LLM METRICS
# ============================================

LLM_REQUESTS = Counter(
    "projectscope_llm_requests_total",
    "Total LLM requests",
    ["provider", "model", "status"],
)

LLM_LATENCY = Histogram(
    "projectscope_llm_latency_seconds",
    "LLM call latency",
    ["provider", "model"],
    buckets=[0.5, 1.0, 2.0, 5.0, 10.0, 30.0, 60.0],
)

LLM_TOKENS = Counter(
    "projectscope_llm_tokens_total",
    "Total LLM tokens consumed",
    ["provider", "model", "type"],  # type: prompt, response
)

LLM_FALLBACKS = Counter(
    "projectscope_llm_fallbacks_total",
    "Number of times fallback provider was used",
    ["primary_provider"],
)


# ============================================
# ML METRICS
# ============================================

ML_PREDICTIONS = Counter(
    "projectscope_ml_predictions_total",
    "Total ML predictions made",
    ["model_name", "status"],
)

ML_PREDICTION_LATENCY = Histogram(
    "projectscope_ml_prediction_duration_seconds",
    "ML prediction latency",
    ["model_name"],
)

ML_PREDICTION_VALUE = Histogram(
    "projectscope_ml_predicted_hours",
    "Distribution of predicted hours",
    ["model_name"],
    buckets=[50, 100, 200, 400, 800, 1600, 3200],
)


# ============================================
# BUSINESS METRICS
# ============================================

PROJECTS_CREATED = Counter(
    "projectscope_projects_created_total",
    "Total projects created",
    ["org_id"],
)

PROJECTS_ANALYZED = Counter(
    "projectscope_projects_analyzed_total",
    "Total projects analyzed",
    ["org_id", "status"],
)

REPORTS_GENERATED = Counter(
    "projectscope_reports_generated_total",
    "Reports generated by format",
    ["format"],
)

USERS_REGISTERED = Counter(
    "projectscope_users_registered_total",
    "Total user registrations",
)

AUTH_ATTEMPTS = Counter(
    "projectscope_auth_attempts_total",
    "Authentication attempts",
    ["status"],  # success, failure
)


# ============================================
# SYSTEM METRICS
# ============================================

DB_QUERIES = Counter(
    "projectscope_db_queries_total",
    "Total database queries",
    ["operation"],
)

DB_QUERY_DURATION = Histogram(
    "projectscope_db_query_duration_seconds",
    "Database query duration",
    ["operation"],
    buckets=[0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0, 5.0],
)

DB_CONNECTION_ERRORS = Counter(
    "projectscope_db_errors_total",
    "Database connection errors",
)

# Cache
CACHE_HITS = Counter("projectscope_cache_hits_total", "Cache hits")
CACHE_MISSES = Counter("projectscope_cache_misses_total", "Cache misses")


# ============================================
# ACTIVE GAUGES
# ============================================

ACTIVE_PROJECTS = Gauge(
    "projectscope_active_projects",
    "Number of active projects",
)

ACTIVE_USERS = Gauge(
    "projectscope_active_users",
    "Number of active users",
)
